apiVersion: apps/v1
kind: StatefulSet
metadata: 
    name: my-db
    labels:
        app: my-app
spec: 
  serviceName: my-db
  replicas: 4
  selector:
       matchLabels:
            app: my-app
  template:   
      metadata:
        labels: 
           app: my-app
        spec:
           containers:
               - name: my-db-container
                 image: mysql:latest
                 ports:
                   - containerPort: 3306
                     protocol: TCP
                 env:
                   - name: MYSQL_ROOT_PASSWORD  
                     value: "123456789"
# without this mysql container will not start this is defult/mindeory 
                             