apiVersion: v1 
kind: persistentVolumeClaim
metadata:
    name: my-pvc
spec:
  storageClassName: efs-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
        