apiVersion: v1
kind: Namespace 
metadata: 
   name: devops
---

apiVersion: v1 
kind: Pod 
metadata: 
  name: dev-pod 
  namespace: devops
  labels: 
   app: dev-test    
spec:
  containers:
   - name: dev-container
     image: nginx:1.28.3
     ports:
       - containerPort: 80 
         port: 80
         protocol: TCP
---
apiVersion: v1 
kind: Service 
metadata:
   name: clusterIP-service
   namespace: devops 
spec: 
  selector: 
   app: dev-test
  type: ClusterIP
  ports:
   - port: 80
     targetPort: 80
     protocol: TCP    
---
apiVersion: v1 
kind: Service 
metadata: 
  name: nodePort-service 
  namespace: devops 
spec: 
  selector: 
    app: dev-test
  type: NodePort
  ports: 
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: v1 
kind: Service 
metadata: 
  name: loadBalancer-service 
  namespace: devops 
spec:  
  selector: 
   app: dev-test
  type: LoadBalancer 
  ports: 
  - port: 80
  targetPort: 80
  protocol: TCP
---



