apiVersion: v1 
kind: PersistentVolume 
metadata:
    name: my-pv 
    labels:
       type: my-pv
spec: 
   storageClassName: standard
   volumeMode: Filesystem  
   capacity:  
            storage: 10Gi      
   accessModes: 
         - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain  #policy for reclaiming the PV after the PVC is deleted
   hostPath: 
         path: "/mnt/data"     #path on the host machine where the data will be stored

