apiVersion: v1 
kind: Namespace
metadata:
    name: my-namespace
    labels:
       app: my-app
---
apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
  labels:
    app: my-app
spec:
  containers:
    - name: my-container
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: TCP