apiVersion: v1 
kind: PersistantVolumeClaim
metadata: 
  name: pv-claim
spec: 
  storageClassName: Standerd 
  volumemode: Filesystem
  accessModes: 
    - ReadwriteOnce
  resources:
    requests:
      storage:10Gi
 
        
  
